-- Script 06_TAB_JSON.sql
-- For presentation duality view
-- Andrea Kennel
-- 21.04.2024

-- DROP VIEW product_flex_dv;
-- DROP TABLE product_flex;
-- ---------------------------------------------------------------------------------------
-- TABLES WITH JSON
-- ---------------------------------------------------------------------------------------

CREATE TABLE product_flex (
  prod_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS 
                              IDENTITY (START WITH 10 INCREMENT BY 1),
  type         VARCHAR2(50),
  name         VARCHAR2(50),
  description  VARCHAR2(200),
  manufacturer VARCHAR2(50),
  price        NUMBER (8,2),
  more_info    JSON
  CONSTRAINT profl_ensure_json CHECK (more_info IS JSON)
);

ALTER TABLE product_flex ADD CONSTRAINT prfl_pk PRIMARY KEY (prod_id);

-- 
-- DUALITY VIEW
-- 

CREATE OR replace json relational DUALITY VIEW product_flex_dv AS
SELECT json {'prod_id'		: p.prod_id,
             'type' 		: p.type,
             'name'   		: p.name,
             'description'	: p.description,
             'manufacturer'	: p.manufacturer,
             'price'		: p.price,
             'more_info'    : p.more_info
            }
FROM product_flex p WITH INSERT UPDATE DELETE;

-- ---------------------------------------------------------------------------------------
-- INSERT
-- ---------------------------------------------------------------------------------------

INSERT INTO product_flex_dv d (data)
VALUES ('
{
        "type": "network switch",
        "name": "Fritz A16",
        "description": "unmanaged 16 port network switch",
        "manufacturer": "ABC",
        "price": 100,
        "more_info": {
        "port_group": [
            {
                "amount": 16,
                "type": "RJ45",
                "speeds": "10/100/1000"
            }
        ]
        }
    }');

INSERT INTO product_flex_dv d (data)
VALUES ('
{
        "type": "router/firewall",
        "name": "Hans A48",
        "description": "48 port HA firewall with advanced filtering, VPN, reverse proxy and docker support",
        "manufacturer": "ABC",
        "price": 500,
        "more_info": {
        "port_group": [
            {
                "amount": 16,
                "type": "RJ45",
                "speeds": "10/100/1000"
            },
            {
                "amount": 16,
                "type": "SFP+",
                "speeds": "1000/40000/100000"
            },
            {
                "amount": 16,
                "type": "SFP",
                "speeds": "1000/10000"
            }
        ],
        "feature": [
            {
                "name": "VLAN",
                "amount": 4094
            },
            {
                "name": "QoS",
                "amount": 8
            },
            {
                "name": "routing",
                "protocols": "static, RIP, OSPF, BGP, EGP",
                "table_size": 1000
            },
            {
                "name": "firewall",
                "type": "stateful, stateless",
                "amount_of_rules": 1000,
                "amount_of_connections": 100000,
                "amount_of_nat_rules": 1000,
                "feature": [
                    {
                        "name": "URL filtering",
                        "types": "whitelist, blacklist",
                        "amount_of_rules": 1000
                    },
                    {
                        "name": "application filtering",
                        "types": "whitelist",
                        "amount_of_rules": 1000
                    },
                    {
                        "name": "content filtering",
                        "types": "blacklist",
                        "amount_of_rules": 1000
                    },
                    {
                        "name": "anti-virus",
                        "ssl_inspection": true
                    }
                ]
            },
            {
                "name": "VPN",
                "type": "IPsec, SSL, L2TP, PPTP",
                "amount_of_tunnels": 1000,
                "amount_of_users": 1000,
                "feature": [
                    {
                        "name": "IPsec",
                        "type": "IKEv1, IKEv2",
                        "amount_of_tunnels": 1000,
                        "amount_of_users": 1000
                    },
                    {
                        "name": "SSL",
                        "amount_of_tunnels": 1000,
                        "amount_of_users": 1000
                    },
                    {
                        "name": "L2TP",
                        "amount_of_tunnels": 1000,
                        "amount_of_users": 1000
                    },
                    {
                        "name": "PPTP",
                        "amount_of_tunnels": 1000,
                        "amount_of_users": 1000
                    }
                ]
            },
            {
                "name": "network access control",
                "type": "MAC based authentication, 802.1x",
                "vlan_support": true
            }
        ]
    }
    }');

COMMIT;

--
-- SELECT 
--

SELECT *
FROM product_flex_dv;

SELECT *
FROM product_flex;