-- Script 03_step3_json_structure.sql
-- For presentation duality views
-- Andrea Kennel
-- 01.10.2024

-- DROP TABLE product_collection;

-- ---------------------------------------------------------------------------------------
-- JSON
-- ---------------------------------------------------------------------------------------

CREATE TABLE product_collection (
  prod_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS 
                              IDENTITY (START WITH 10 INCREMENT BY 1),
  json_data    JSON
  CONSTRAINT pro_ensure_json CHECK (json_data IS JSON)
);

ALTER TABLE product_collection ADD CONSTRAINT prco_pk PRIMARY KEY (prod_id);

-- ---------------------------------------------------------------------------------------
-- INSERT
-- ---------------------------------------------------------------------------------------

INSERT INTO product_collection (json_data)
VALUES ('
{
        "type": "network switch",
        "name": "Fritz A16",
        "description": "unmanaged 16 port network switch",
        "manufacturer": "ABC",
        "price": 100,
        "port_group": [
            {
                "amount": 16,
                "type": "RJ45",
                "speeds": "10/100/1000"
            }
        ]
    }');

INSERT INTO product_collection (json_data)
VALUES ('
{
        "type": "network switch",
        "name": "Fritz B24",
        "description": "unmanaged 24 port 10gbit/s network switch",
        "manufacturer": "ABC",
        "price": 250,
        "port_group": [
            {
                "amount": 24,
                "type": "RJ45",
                "speeds": "10/100/1000/2500/5000/10000"
            }
        ]
    }');
    
INSERT INTO product_collection (json_data)
VALUES ('
{       "type": "network switch",
        "name": "Fritz C12",
        "description": "managed 12 port network switch",
        "manufacturer": "DEF",
        "price": 150,
        "port_group": [
            {   "amount": 12,
                "type": "RJ45",
                "speeds": "10/100/1000/10000"
            },
            {   "amount": 2,
                "type": "SFP",
                "speeds": "1000/10000"
            } ]
    }');

INSERT INTO product_collection (json_data)
VALUES ('
{       "type": "router",
        "name": "Hans A8",
        "description": "8 port router",
        "manufacturer": "ABC",
        "price": 1000,
        "port_group": [
            {   "amount": 4,
                "type": "RJ45",
                "speeds": "100/1000/10000"
            },
            {   "amount": 2,
                "type": "SFP+",
                "speeds": "1000/40000/100000"
            },
            {   "amount": 2,
                "type": "SFP",
                "speeds": "1000/10000"
            } ],
        "routing": {
            "protocols": "static, RIP, OSPF, BGP",
            "table_size": 10
        }
    }');

INSERT INTO product_collection (json_data)
VALUES ('
{
        "type": "router",
        "name": "Hans B4",
        "description": "4 port router",
        "manufacturer": "XYZ",
        "price": 800,
        "port_group": [
            {
                "amount": 4,
                "type": "RJ45",
                "speeds": "100/1000"
            },
            {
                "amount": 2,
                "type": "SFP",
                "speeds": "1000/10000"
            }
        ],
        "routing": {
            "protocols": "static OSPF",
            "table_size": 5
        }
    }');

COMMIT;

SELECT * FROM product_collection;
